on:
    push:
      branches:
        - main
    pull_request:
        branches:
            - main
    schedule:
      - cron: '0 12 * * 1'
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@v3
        with:
          extra_args: --results=verified,unknown
          scan_args: --regex --entropy=False