name: "Secret Scanning"

on: [push, pull_request]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Scan for Secrets
      uses: trufflesecurity/trufflehog@v3
      with:
        scanArguments: "--regex --entropy=False"
    
