name: FrontendTesting
run-name: ${{ github.actor }} is testing their frontend
on: [push]
jobs:
  run-defined-frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm cache clean --force
      - run: npm ci
      - run: npm run test
